Position.create!([
  {description: "Secretaria"},
  {description: "Programador"}
])
Rol.create!([
  {description: "Super Usuario"},
  {description: "Administrador"},
  {description: "Usuario"}
])
TipoPersona.create!([
  {description: "Natural"},
  {description: "Juridica"}
])
PaisOrigen.create!([
  {description: "Afghanistan"},
  {description: "Albania"},
  {description: "Algeria"},
  {description: "Andorra"},
  {description: "Angola"},
  {description: "Antigua and Barbuda"},
  {description: "Argentina"},
  {description: "Armenia"},
  {description: "Australia"},
  {description: "Austria"},
  {description: "Azerbaijan"},
  {description: "Bahamas, The"},
  {description: "Bahrain"},
  {description: "Bangladesh"},
  {description: "Barbados"},
  {description: "Belarus"},
  {description: "Belgium"},
  {description: "Belize"},
  {description: "Benin"},
  {description: "Bhutan"},
  {description: "Bolivia"},
  {description: "Bosnia and Herzegovina"},
  {description: "Botswana"},
  {description: "Brazil"},
  {description: "Brunei"},
  {description: "Bulgaria"},
  {description: "Burkina Faso"},
  {description: "Burma"},
  {description: "Burundi"},
  {description: "Cambodia"},
  {description: "Cameroon"},
  {description: "Canada"},
  {description: "Cape Verde"},
  {description: "Central Africa"},
  {description: "Chad"},
  {description: "Chile"},
  {description: "China"},
  {description: "Colombia"},
  {description: "Comoros"},
  {description: "Congo, Democratic Republic of the"},
  {description: "Costa Rica"},
  {description: "Cote dIvoire"},
  {description: "Crete"},
  {description: "Croatia"},
  {description: "Cuba"},
  {description: "Cyprus"},
  {description: "Czech Republic"},
  {description: "Denmark"},
  {description: "Djibouti"},
  {description: "Dominican Republic"},
  {description: "East Timor"},
  {description: "Ecuador"},
  {description: "Egypt"},
  {description: "El Salvador"},
  {description: "Equatorial Guinea"},
  {description: "Eritrea"},
  {description: "Estonia"},
  {description: "Ethiopia"},
  {description: "Fiji"},
  {description: "Finland"},
  {description: "France"},
  {description: "Gabon"},
  {description: "Gambia, The"},
  {description: "Georgia"},
  {description: "Germany"},
  {description: "Ghana"},
  {description: "Greece"},
  {description: "Grenada"},
  {description: "Guadeloupe"},
  {description: "Guatemala"},
  {description: "Guinea"},
  {description: "Guinea-Bissau"},
  {description: "Guyana"},
  {description: "Haiti"},
  {description: "Holy See"},
  {description: "Honduras"},
  {description: "Hong Kong"},
  {description: "Hungary"},
  {description: "Iceland"},
  {description: "India"},
  {description: "Indonesia"},
  {description: "Iran"},
  {description: "Iraq"},
  {description: "Ireland"},
  {description: "Israel"},
  {description: "Italy"},
  {description: "Ivory Coast"},
  {description: "Jamaica"},
  {description: "Japan"},
  {description: "Jordan"},
  {description: "Kazakhstan"},
  {description: "Kenya"},
  {description: "Kiribati"},
  {description: "Korea, North"},
  {description: "Korea, South"},
  {description: "Kosovo"},
  {description: "Kuwait"},
  {description: "Kyrgyzstan"},
  {description: "Laos"},
  {description: "Latvia"},
  {description: "Lebanon"},
  {description: "Lesotho"},
  {description: "Liberia"},
  {description: "Libya"},
  {description: "Liechtenstein"},
  {description: "Lithuania"},
  {description: "Macau"},
  {description: "Macedonia"},
  {description: "Madagascar"},
  {description: "Malawi"},
  {description: "Malaysia"},
  {description: "Maldives"},
  {description: "Mali"},
  {description: "Malta"},
  {description: "Marshall Islands"},
  {description: "Mauritania"},
  {description: "Mauritius"},
  {description: "Mexico"},
  {description: "Micronesia"},
  {description: "Moldova"},
  {description: "Monaco"},
  {description: "Mongolia"},
  {description: "Montenegro"},
  {description: "Morocco"},
  {description: "Mozambique"},
  {description: "Namibia"},
  {description: "Nauru"},
  {description: "Nepal"},
  {description: "Netherlands"},
  {description: "New Zealand"},
  {description: "Nicaragua"},
  {description: "Niger"},
  {description: "Nigeria"},
  {description: "North Korea"},
  {description: "Norway"},
  {description: "Oman"},
  {description: "Pakistan"},
  {description: "Palau"},
  {description: "Panama"},
  {description: "Papua New Guinea"},
  {description: "Paraguay"},
  {description: "Peru"},
  {description: "Philippines"},
  {description: "Poland"},
  {description: "Portugal"},
  {description: "Qatar"},
  {description: "Romania"},
  {description: "Russia"},
  {description: "Rwanda"},
  {description: "Saint Lucia"},
  {description: "Saint Vincent and the Grenadines"},
  {description: "Samoa"},
  {description: "San Marino"},
  {description: "Sao Tome and Principe"},
  {description: "Saudi Arabia"},
  {description: "Scotland"},
  {description: "Senegal"},
  {description: "Serbia"},
  {description: "Seychelles"},
  {description: "Sierra Leone"},
  {description: "Singapore"},
  {description: "Slovakia"},
  {description: "Slovenia"},
  {description: "Solomon Islands"},
  {description: "Somalia"},
  {description: "South Africa"},
  {description: "South Korea"},
  {description: "Spain"},
  {description: "Sri Lanka"},
  {description: "Sudan"},
  {description: "Suriname"},
  {description: "Swaziland"},
  {description: "Sweden"},
  {description: "Switzerland"},
  {description: "Syria"},
  {description: "Taiwan"},
  {description: "Tajikistan"},
  {description: "Tanzania"},
  {description: "Thailand"},
  {description: "Tibet"},
  {description: "Timor-Leste"},
  {description: "Togo"},
  {description: "Tonga"},
  {description: "Trinidad and Tobago"},
  {description: "Tunisia"},
  {description: "Turkey"},
  {description: "Turkmenistan"},
  {description: "Tuvalu"},
  {description: "Uganda"},
  {description: "Ukraine"},
  {description: "United Arab Emirates"},
  {description: "United Kingdom"},
  {description: "United States"},
  {description: "Uruguay"},
  {description: "Uzbekistan"},
  {description: "Vanuatu"},
  {description: "Venezuela"},
  {description: "Vietnam"},
  {description: "Yemen"},
  {description: "Zambia"},
  {description: "Zimbabwe"}
])
User.create!([
  {name: "Developer", description: nil, surname: nil, user_name: "developer_dev", password: "6a46b90819aa8554dcdb6791a47749a8", rol_id: 1, email: "developer@developer.com", encrypted_password: "6a46b90819aa8554dcdb6791a47749a8", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 9, current_sign_in_at: "2017-09-09 02:20:59", last_sign_in_at: "2017-09-08 04:35:15", current_sign_in_ip: "::1", last_sign_in_ip: "::1"},
  {name: "Administrador", description: nil, surname: nil, user_name: nil, password: "2e3a55ddb1b933e1a358ef57ebed4b07", rol_id: 2, email: "administrador@administrador.com", encrypted_password: "2e3a55ddb1b933e1a358ef57ebed4b07", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 8, current_sign_in_at: "2017-09-10 20:02:15", last_sign_in_at: "2017-09-09 04:48:51", current_sign_in_ip: "::1", last_sign_in_ip: "::1"},
  {name: "Usuario", description: "Usuario normal", surname: nil, user_name: nil, password: "c0dde08d50ef1c554d6f36513e5e3e36", rol_id: 3, email: "usuario@usuario.com", encrypted_password: "c0dde08d50ef1c554d6f36513e5e3e36", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil}
])


Ciudad.create!([
  {description: "Ahuachapán", pais_origens_id: 1},
  {description: "Jujutla", pais_origens_id: 1},
  {description: "Atiquizaya", pais_origens_id: 1},
  {description: "Concepción de Ataco", pais_origens_id: 1},
  {description: "El Refugio", pais_origens_id: 1},
  {description: "Guaymango", pais_origens_id: 1},
  {description: "Apaneca", pais_origens_id: 1},
  {description: "San Francisco Menéndez", pais_origens_id: 1},
  {description: "San Lorenzo", pais_origens_id: 1},
  {description: "San Pedro Puxtla", pais_origens_id: 1},
  {description: "Tacuba", pais_origens_id: 1},
  {description: "Turín", pais_origens_id: 1},
  {description: "Candelaria de la Frontera", pais_origens_id: 1},
  {description: "Chalchuapa", pais_origens_id: 1},
  {description: "Coatepeque", pais_origens_id: 1},
  {description: "El Congo", pais_origens_id: 1},
  {description: "El Porvenir", pais_origens_id: 1},
  {description: "Masahuat", pais_origens_id: 1},
  {description: "Metapán", pais_origens_id: 1},
  {description: "San Antonio Pajonal", pais_origens_id: 1},
  {description: "San Sebastián Salitrillo", pais_origens_id: 1},
  {description: "Santa Ana", pais_origens_id: 1},
  {description: "Santa Rosa Guachipilín", pais_origens_id: 1},
  {description: "Santiago de la Frontera", pais_origens_id: 1},
  {description: "Texistepeque", pais_origens_id: 1},
  {description: "Acajutla", pais_origens_id: 1},
  {description: "Armenia", pais_origens_id: 1},
  {description: "Caluco", pais_origens_id: 1},
  {description: "Cuisnahuat", pais_origens_id: 1},
  {description: "Izalco", pais_origens_id: 1},
  {description: "Juayúa", pais_origens_id: 1},
  {description: "Nahuizalco", pais_origens_id: 1},
  {description: "Nahulingo", pais_origens_id: 1},
  {description: "Salcoatitán", pais_origens_id: 1},
  {description: "San Antonio del Monte", pais_origens_id: 1},
  {description: "San Julián", pais_origens_id: 1},
  {description: "Santa Catarina Masahuat", pais_origens_id: 1},
  {description: "Santa Isabel Ishuatán", pais_origens_id: 1},
  {description: "Santo Domingo de Guzmán", pais_origens_id: 1},
  {description: "Sonsonate", pais_origens_id: 1},
  {description: "Sonzacate", pais_origens_id: 1},
  {description: "Alegría", pais_origens_id: 1},
  {description: "Berlín", pais_origens_id: 1},
  {description: "California", pais_origens_id: 1},
  {description: "Concepción Batres", pais_origens_id: 1},
  {description: "El Triunfo", pais_origens_id: 1},
  {description: "Ereguayquín", pais_origens_id: 1},
  {description: "Estanzuelas", pais_origens_id: 1},
  {description: "Jiquilisco", pais_origens_id: 1},
  {description: "Jucuapa", pais_origens_id: 1},
  {description: "Jucuarán", pais_origens_id: 1},
  {description: "Mercedes Umaña", pais_origens_id: 1},
  {description: "Nueva Granada", pais_origens_id: 1},
  {description: "Ozatlán", pais_origens_id: 1},
  {description: "Puerto El Triunfo", pais_origens_id: 1},
  {description: "San Agustín", pais_origens_id: 1},
  {description: "San Buenaventura", pais_origens_id: 1},
  {description: "San Dionisio", pais_origens_id: 1},
  {description: "San Francisco Javier", pais_origens_id: 1},
  {description: "Santa Elena", pais_origens_id: 1},
  {description: "Santa María", pais_origens_id: 1},
  {description: "Santiago de María", pais_origens_id: 1},
  {description: "Tecapán", pais_origens_id: 1},
  {description: "Usulután", pais_origens_id: 1},
  {description: "Carolina", pais_origens_id: 1},
  {description: "Chapeltique", pais_origens_id: 1},
  {description: "Chinameca", pais_origens_id: 1},
  {description: "Chirilagua", pais_origens_id: 1},
  {description: "Ciudad Barrios", pais_origens_id: 1},
  {description: "Comacarán", pais_origens_id: 1},
  {description: "El Tránsito", pais_origens_id: 1},
  {description: "Lolotique", pais_origens_id: 1},
  {description: "Moncagua", pais_origens_id: 1},
  {description: "Nueva Guadalupe", pais_origens_id: 1},
  {description: "Nuevo Edén de San Juan", pais_origens_id: 1},
  {description: "Quelepa", pais_origens_id: 1},
  {description: "San Antonio del Mosco", pais_origens_id: 1},
  {description: "San Gerardo", pais_origens_id: 1},
  {description: "San Jorge", pais_origens_id: 1},
  {description: "San Luis de la Reina", pais_origens_id: 1},
  {description: "San Miguel", pais_origens_id: 1},
  {description: "San Rafael Oriente", pais_origens_id: 1},
  {description: "Sesori", pais_origens_id: 1},
  {description: "Uluazapa", pais_origens_id: 1},
  {description: "Arambala", pais_origens_id: 1},
  {description: "Cacaopera", pais_origens_id: 1},
  {description: "Chilanga", pais_origens_id: 1},
  {description: "Corinto", pais_origens_id: 1},
  {description: "Delicias de Concepción", pais_origens_id: 1},
  {description: "El Divisadero", pais_origens_id: 1},
  {description: "El Rosario (Morazán)", pais_origens_id: 1},
  {description: "Gualococti", pais_origens_id: 1},
  {description: "Guatajiagua", pais_origens_id: 1},
  {description: "Joateca", pais_origens_id: 1},
  {description: "Jocoaitique", pais_origens_id: 1},
  {description: "Jocoro", pais_origens_id: 1},
  {description: "Lolotiquillo", pais_origens_id: 1},
  {description: "Meanguera", pais_origens_id: 1},
  {description: "Osicala", pais_origens_id: 1},
  {description: "Perquín", pais_origens_id: 1},
  {description: "San Carlos", pais_origens_id: 1},
  {description: "San Fernando (Morazán)", pais_origens_id: 1},
  {description: "San Francisco Gotera", pais_origens_id: 1},
  {description: "San Isidro (Morazán)", pais_origens_id: 1},
  {description: "San Simón", pais_origens_id: 1},
  {description: "Sensembra", pais_origens_id: 1},
  {description: "Sociedad", pais_origens_id: 1},
  {description: "Torola", pais_origens_id: 1},
  {description: "Yamabal", pais_origens_id: 1},
  {description: "Yoloaiquín", pais_origens_id: 1},
  {description: "La Unión", pais_origens_id: 1},
  {description: "San Alejo", pais_origens_id: 1},
  {description: "Yucuaiquín", pais_origens_id: 1},
  {description: "Conchagua", pais_origens_id: 1},
  {description: "Intipucá", pais_origens_id: 1},
  {description: "San José", pais_origens_id: 1},
  {description: "El Carmen (La Unión)", pais_origens_id: 1},
  {description: "Yayantique", pais_origens_id: 1},
  {description: "Bolívar", pais_origens_id: 1},
  {description: "Meanguera del Golfo", pais_origens_id: 1},
  {description: "Santa Rosa de Lima", pais_origens_id: 1},
  {description: "Pasaquina", pais_origens_id: 1},
  {description: "Anamoros", pais_origens_id: 1},
  {description: "Nueva Esparta", pais_origens_id: 1},
  {description: "El Sauce", pais_origens_id: 1},
  {description: "Concepción de Oriente", pais_origens_id: 1},
  {description: "Polorós", pais_origens_id: 1},
  {description: "Lislique", pais_origens_id: 1},
  {description: "Antiguo Cuscatlán", pais_origens_id: 1},
  {description: "Chiltiupán", pais_origens_id: 1},
  {description: "Ciudad Arce", pais_origens_id: 1},
  {description: "Colón", pais_origens_id: 1},
  {description: "Comasagua", pais_origens_id: 1},
  {description: "Huizúcar", pais_origens_id: 1},
  {description: "Jayaque", pais_origens_id: 1},
  {description: "Jicalapa", pais_origens_id: 1},
  {description: "La Libertad", pais_origens_id: 1},
  {description: "Santa Tecla", pais_origens_id: 1},
  {description: "Nuevo Cuscatlán", pais_origens_id: 1},
  {description: "San Juan Opico", pais_origens_id: 1},
  {description: "Quezaltepeque", pais_origens_id: 1},
  {description: "Sacacoyo", pais_origens_id: 1},
  {description: "San José Villanueva", pais_origens_id: 1},
  {description: "San Matías", pais_origens_id: 1},
  {description: "San Pablo Tacachico", pais_origens_id: 1},
  {description: "Talnique", pais_origens_id: 1},
  {description: "Tamanique", pais_origens_id: 1},
  {description: "Teotepeque", pais_origens_id: 1},
  {description: "Tepecoyo", pais_origens_id: 1},
  {description: "Zaragoza", pais_origens_id: 1},
  {description: "Agua Caliente", pais_origens_id: 1},
  {description: "Arcatao", pais_origens_id: 1},
  {description: "Azacualpa", pais_origens_id: 1},
  {description: "Cancasque", pais_origens_id: 1},
  {description: "Chalatenango", pais_origens_id: 1},
  {description: "Citalá", pais_origens_id: 1},
  {description: "Comapala", pais_origens_id: 1},
  {description: "Concepción Quezaltepeque", pais_origens_id: 1},
  {description: "Dulce Nombre de María", pais_origens_id: 1},
  {description: "El Carrizal", pais_origens_id: 1},
  {description: "El Paraíso", pais_origens_id: 1},
  {description: "La Laguna", pais_origens_id: 1},
  {description: "La Palma", pais_origens_id: 1},
  {description: "La Reina", pais_origens_id: 1},
  {description: "Las Vueltas", pais_origens_id: 1},
  {description: "Nueva Concepción", pais_origens_id: 1},
  {description: "Nueva Trinidad", pais_origens_id: 1},
  {description: "Nombre de Jesús", pais_origens_id: 1},
  {description: "Ojos de Agua", pais_origens_id: 1},
  {description: "Potonico", pais_origens_id: 1},
  {description: "San Antonio de la Cruz", pais_origens_id: 1},
  {description: "San Antonio Los Ranchos", pais_origens_id: 1},
  {description: "San Fernando (Chalatenango)", pais_origens_id: 1},
  {description: "San Francisco Lempa", pais_origens_id: 1},
  {description: "San Francisco Morazán", pais_origens_id: 1},
  {description: "San Ignacio", pais_origens_id: 1},
  {description: "San Isidro Labrador", pais_origens_id: 1},
  {description: "Las Flores", pais_origens_id: 1},
  {description: "San Luis del Carmen", pais_origens_id: 1},
  {description: "San Miguel de Mercedes", pais_origens_id: 1},
  {description: "San Rafael", pais_origens_id: 1},
  {description: "Santa Rita", pais_origens_id: 1},
  {description: "Tejutla", pais_origens_id: 1},
  {description: "Cojutepeque", pais_origens_id: 1},
  {description: "Candelaria", pais_origens_id: 1},
  {description: "El Carmen (Cuscatlán)", pais_origens_id: 1},
  {description: "El Rosario (Cuscatlán)", pais_origens_id: 1},
  {description: "Monte San Juan", pais_origens_id: 1},
  {description: "Oratorio de Concepción", pais_origens_id: 1},
  {description: "San Bartolomé Perulapía", pais_origens_id: 1},
  {description: "San Cristóbal", pais_origens_id: 1},
  {description: "San José Guayabal", pais_origens_id: 1},
  {description: "San Pedro Perulapán", pais_origens_id: 1},
  {description: "San Rafael Cedros", pais_origens_id: 1},
  {description: "San Ramón", pais_origens_id: 1},
  {description: "Santa Cruz Analquito", pais_origens_id: 1},
  {description: "Santa Cruz Michapa", pais_origens_id: 1},
  {description: "Suchitoto", pais_origens_id: 1},
  {description: "Tenancingo", pais_origens_id: 1},
  {description: "Aguilares", pais_origens_id: 1},
  {description: "Apopa", pais_origens_id: 1},
  {description: "Ayutuxtepeque", pais_origens_id: 1},
  {description: "Cuscatancingo", pais_origens_id: 1},
  {description: "Ciudad Delgado", pais_origens_id: 1},
  {description: "El Paisnal", pais_origens_id: 1},
  {description: "Guazapa", pais_origens_id: 1},
  {description: "Ilopango", pais_origens_id: 1},
  {description: "Mejicanos", pais_origens_id: 1},
  {description: "Ahuachapán", pais_origens_id: 1},
  {description: "Jujutla", pais_origens_id: 1},
  {description: "Atiquizaya", pais_origens_id: 1},
  {description: "Concepción de Ataco", pais_origens_id: 1},
  {description: "El Refugio", pais_origens_id: 1},
  {description: "Guaymango", pais_origens_id: 1},
  {description: "Apaneca", pais_origens_id: 1},
  {description: "San Francisco Menéndez", pais_origens_id: 1},
  {description: "San Lorenzo", pais_origens_id: 1},
  {description: "San Pedro Puxtla", pais_origens_id: 1},
  {description: "Tacuba", pais_origens_id: 1},
  {description: "Turín", pais_origens_id: 1},
  {description: "Candelaria de la Frontera", pais_origens_id: 1},
  {description: "Chalchuapa", pais_origens_id: 1},
  {description: "Coatepeque", pais_origens_id: 1},
  {description: "El Congo", pais_origens_id: 1},
  {description: "El Porvenir", pais_origens_id: 1},
  {description: "Masahuat", pais_origens_id: 1},
  {description: "Metapán", pais_origens_id: 1},
  {description: "San Antonio Pajonal", pais_origens_id: 1},
  {description: "San Sebastián Salitrillo", pais_origens_id: 1},
  {description: "Santa Ana", pais_origens_id: 1},
  {description: "Santa Rosa Guachipilín", pais_origens_id: 1},
  {description: "Santiago de la Frontera", pais_origens_id: 1},
  {description: "Texistepeque", pais_origens_id: 1},
  {description: "Acajutla", pais_origens_id: 1},
  {description: "Armenia", pais_origens_id: 1},
  {description: "Caluco", pais_origens_id: 1},
  {description: "Cuisnahuat", pais_origens_id: 1},
  {description: "Izalco", pais_origens_id: 1},
  {description: "Juayúa", pais_origens_id: 1},
  {description: "Nahuizalco", pais_origens_id: 1},
  {description: "Nahulingo", pais_origens_id: 1},
  {description: "Salcoatitán", pais_origens_id: 1},
  {description: "San Antonio del Monte", pais_origens_id: 1},
  {description: "San Julián", pais_origens_id: 1},
  {description: "Santa Catarina Masahuat", pais_origens_id: 1},
  {description: "Santa Isabel Ishuatán", pais_origens_id: 1},
  {description: "Santo Domingo de Guzmán", pais_origens_id: 1},
  {description: "Sonsonate", pais_origens_id: 1},
  {description: "Sonzacate", pais_origens_id: 1},
  {description: "Alegría", pais_origens_id: 1},
  {description: "Berlín", pais_origens_id: 1},
  {description: "California", pais_origens_id: 1},
  {description: "Concepción Batres", pais_origens_id: 1},
  {description: "El Triunfo", pais_origens_id: 1},
  {description: "Ereguayquín", pais_origens_id: 1},
  {description: "Estanzuelas", pais_origens_id: 1},
  {description: "Jiquilisco", pais_origens_id: 1},
  {description: "Jucuapa", pais_origens_id: 1},
  {description: "Jucuarán", pais_origens_id: 1},
  {description: "Mercedes Umaña", pais_origens_id: 1},
  {description: "Nueva Granada", pais_origens_id: 1},
  {description: "Ozatlán", pais_origens_id: 1},
  {description: "Puerto El Triunfo", pais_origens_id: 1},
  {description: "San Agustín", pais_origens_id: 1},
  {description: "San Buenaventura", pais_origens_id: 1},
  {description: "San Dionisio", pais_origens_id: 1},
  {description: "San Francisco Javier", pais_origens_id: 1},
  {description: "Santa Elena", pais_origens_id: 1},
  {description: "Santa María", pais_origens_id: 1},
  {description: "Santiago de María", pais_origens_id: 1},
  {description: "Tecapán", pais_origens_id: 1},
  {description: "Usulután", pais_origens_id: 1},
  {description: "Carolina", pais_origens_id: 1},
  {description: "Chapeltique", pais_origens_id: 1},
  {description: "Chinameca", pais_origens_id: 1},
  {description: "Chirilagua", pais_origens_id: 1},
  {description: "Ciudad Barrios", pais_origens_id: 1},
  {description: "Comacarán", pais_origens_id: 1},
  {description: "El Tránsito", pais_origens_id: 1},
  {description: "Lolotique", pais_origens_id: 1},
  {description: "Moncagua", pais_origens_id: 1},
  {description: "Nueva Guadalupe", pais_origens_id: 1},
  {description: "Nuevo Edén de San Juan", pais_origens_id: 1},
  {description: "Quelepa", pais_origens_id: 1},
  {description: "San Antonio del Mosco", pais_origens_id: 1},
  {description: "San Gerardo", pais_origens_id: 1},
  {description: "San Jorge", pais_origens_id: 1},
  {description: "San Luis de la Reina", pais_origens_id: 1},
  {description: "San Miguel", pais_origens_id: 1},
  {description: "San Rafael Oriente", pais_origens_id: 1},
  {description: "Sesori", pais_origens_id: 1},
  {description: "Uluazapa", pais_origens_id: 1},
  {description: "Arambala", pais_origens_id: 1},
  {description: "Cacaopera", pais_origens_id: 1},
  {description: "Chilanga", pais_origens_id: 1},
  {description: "Corinto", pais_origens_id: 1},
  {description: "Delicias de Concepción", pais_origens_id: 1},
  {description: "El Divisadero", pais_origens_id: 1},
  {description: "El Rosario (Morazán)", pais_origens_id: 1},
  {description: "Gualococti", pais_origens_id: 1},
  {description: "Guatajiagua", pais_origens_id: 1},
  {description: "Joateca", pais_origens_id: 1},
  {description: "Jocoaitique", pais_origens_id: 1},
  {description: "Jocoro", pais_origens_id: 1},
  {description: "Lolotiquillo", pais_origens_id: 1},
  {description: "Meanguera", pais_origens_id: 1},
  {description: "Osicala", pais_origens_id: 1},
  {description: "Perquín", pais_origens_id: 1},
  {description: "San Carlos", pais_origens_id: 1},
  {description: "San Fernando (Morazán)", pais_origens_id: 1},
  {description: "San Francisco Gotera", pais_origens_id: 1},
  {description: "San Isidro (Morazán)", pais_origens_id: 1},
  {description: "San Simón", pais_origens_id: 1},
  {description: "Sensembra", pais_origens_id: 1},
  {description: "Sociedad", pais_origens_id: 1},
  {description: "Torola", pais_origens_id: 1},
  {description: "Yamabal", pais_origens_id: 1},
  {description: "Yoloaiquín", pais_origens_id: 1},
  {description: "La Unión", pais_origens_id: 1},
  {description: "San Alejo", pais_origens_id: 1},
  {description: "Yucuaiquín", pais_origens_id: 1},
  {description: "Conchagua", pais_origens_id: 1},
  {description: "Intipucá", pais_origens_id: 1},
  {description: "San José", pais_origens_id: 1},
  {description: "El Carmen (La Unión)", pais_origens_id: 1},
  {description: "Yayantique", pais_origens_id: 1},
  {description: "Bolívar", pais_origens_id: 1},
  {description: "Meanguera del Golfo", pais_origens_id: 1},
  {description: "Santa Rosa de Lima", pais_origens_id: 1},
  {description: "Pasaquina", pais_origens_id: 1},
  {description: "Anamoros", pais_origens_id: 1},
  {description: "Nueva Esparta", pais_origens_id: 1},
  {description: "El Sauce", pais_origens_id: 1},
  {description: "Concepción de Oriente", pais_origens_id: 1},
  {description: "Polorós", pais_origens_id: 1},
  {description: "Lislique", pais_origens_id: 1},
  {description: "Antiguo Cuscatlán", pais_origens_id: 1},
  {description: "Chiltiupán", pais_origens_id: 1},
  {description: "Ciudad Arce", pais_origens_id: 1},
  {description: "Colón", pais_origens_id: 1},
  {description: "Comasagua", pais_origens_id: 1},
  {description: "Huizúcar", pais_origens_id: 1},
  {description: "Jayaque", pais_origens_id: 1},
  {description: "Jicalapa", pais_origens_id: 1},
  {description: "La Libertad", pais_origens_id: 1},
  {description: "Santa Tecla", pais_origens_id: 1},
  {description: "Nuevo Cuscatlán", pais_origens_id: 1},
  {description: "San Juan Opico", pais_origens_id: 1},
  {description: "Quezaltepeque", pais_origens_id: 1},
  {description: "Sacacoyo", pais_origens_id: 1},
  {description: "San José Villanueva", pais_origens_id: 1},
  {description: "San Matías", pais_origens_id: 1},
  {description: "San Pablo Tacachico", pais_origens_id: 1},
  {description: "Talnique", pais_origens_id: 1},
  {description: "Tamanique", pais_origens_id: 1},
  {description: "Teotepeque", pais_origens_id: 1},
  {description: "Tepecoyo", pais_origens_id: 1},
  {description: "Zaragoza", pais_origens_id: 1},
  {description: "Agua Caliente", pais_origens_id: 1},
  {description: "Arcatao", pais_origens_id: 1},
  {description: "Azacualpa", pais_origens_id: 1},
  {description: "Cancasque", pais_origens_id: 1},
  {description: "Chalatenango", pais_origens_id: 1},
  {description: "Citalá", pais_origens_id: 1},
  {description: "Comapala", pais_origens_id: 1},
  {description: "Concepción Quezaltepeque", pais_origens_id: 1},
  {description: "Dulce Nombre de María", pais_origens_id: 1},
  {description: "El Carrizal", pais_origens_id: 1},
  {description: "El Paraíso", pais_origens_id: 1},
  {description: "La Laguna", pais_origens_id: 1},
  {description: "La Palma", pais_origens_id: 1},
  {description: "La Reina", pais_origens_id: 1},
  {description: "Las Vueltas", pais_origens_id: 1},
  {description: "Nueva Concepción", pais_origens_id: 1},
  {description: "Nueva Trinidad", pais_origens_id: 1},
  {description: "Nombre de Jesús", pais_origens_id: 1},
  {description: "Ojos de Agua", pais_origens_id: 1},
  {description: "Potonico", pais_origens_id: 1},
  {description: "San Antonio de la Cruz", pais_origens_id: 1},
  {description: "San Antonio Los Ranchos", pais_origens_id: 1},
  {description: "San Fernando (Chalatenango)", pais_origens_id: 1},
  {description: "San Francisco Lempa", pais_origens_id: 1},
  {description: "San Francisco Morazán", pais_origens_id: 1},
  {description: "San Ignacio", pais_origens_id: 1},
  {description: "San Isidro Labrador", pais_origens_id: 1},
  {description: "Las Flores", pais_origens_id: 1},
  {description: "San Luis del Carmen", pais_origens_id: 1},
  {description: "San Miguel de Mercedes", pais_origens_id: 1},
  {description: "San Rafael", pais_origens_id: 1},
  {description: "Santa Rita", pais_origens_id: 1},
  {description: "Tejutla", pais_origens_id: 1},
  {description: "Cojutepeque", pais_origens_id: 1},
  {description: "Candelaria", pais_origens_id: 1},
  {description: "El Carmen (Cuscatlán)", pais_origens_id: 1},
  {description: "El Rosario (Cuscatlán)", pais_origens_id: 1},
  {description: "Monte San Juan", pais_origens_id: 1},
  {description: "Oratorio de Concepción", pais_origens_id: 1},
  {description: "San Bartolomé Perulapía", pais_origens_id: 1},
  {description: "San Cristóbal", pais_origens_id: 1},
  {description: "San José Guayabal", pais_origens_id: 1},
  {description: "San Pedro Perulapán", pais_origens_id: 1},
  {description: "San Rafael Cedros", pais_origens_id: 1},
  {description: "San Ramón", pais_origens_id: 1},
  {description: "Santa Cruz Analquito", pais_origens_id: 1},
  {description: "Santa Cruz Michapa", pais_origens_id: 1},
  {description: "Suchitoto", pais_origens_id: 1},
  {description: "Tenancingo", pais_origens_id: 1},
  {description: "Aguilares", pais_origens_id: 1},
  {description: "Apopa", pais_origens_id: 1},
  {description: "Ayutuxtepeque", pais_origens_id: 1},
  {description: "Cuscatancingo", pais_origens_id: 1},
  {description: "Ciudad Delgado", pais_origens_id: 1},
  {description: "El Paisnal", pais_origens_id: 1},
  {description: "Guazapa", pais_origens_id: 1},
  {description: "Ilopango", pais_origens_id: 1},
  {description: "Mejicanos", pais_origens_id: 1},
  {description: "Nejapa", pais_origens_id: 1},
  {description: "Panchimalco", pais_origens_id: 1},
  {description: "Rosario de Mora", pais_origens_id: 1},
  {description: "San Marcos", pais_origens_id: 1},
  {description: "San Martín", pais_origens_id: 1},
  {description: "San Salvador", pais_origens_id: 1},
  {description: "Santiago Texacuangos", pais_origens_id: 1},
  {description: "Santo Tomás", pais_origens_id: 1},
  {description: "Soyapango", pais_origens_id: 1},
  {description: "Tonacatepeque", pais_origens_id: 1},
  {description: "Zacatecoluca", pais_origens_id: 1},
  {description: "Cuyultitán", pais_origens_id: 1},
  {description: "El Rosario (La Paz)", pais_origens_id: 1},
  {description: "Jerusalén", pais_origens_id: 1},
  {description: "Mercedes La Ceiba", pais_origens_id: 1},
  {description: "Olocuilta", pais_origens_id: 1},
  {description: "Paraíso de Osorio", pais_origens_id: 1},
  {description: "San Antonio Masahuat", pais_origens_id: 1},
  {description: "San Emigdio", pais_origens_id: 1},
  {description: "San Francisco Chinameca", pais_origens_id: 1},
  {description: "San Pedro Masahuat", pais_origens_id: 1},
  {description: "San Juan Nonualco", pais_origens_id: 1},
  {description: "San Juan Talpa", pais_origens_id: 1},
  {description: "San Juan Tepezontes", pais_origens_id: 1},
  {description: "San Luis La Herradura", pais_origens_id: 1},
  {description: "San Luis Talpa", pais_origens_id: 1},
  {description: "San Miguel Tepezontes", pais_origens_id: 1},
  {description: "San Pedro Nonualco", pais_origens_id: 1},
  {description: "San Rafael Obrajuelo", pais_origens_id: 1},
  {description: "Santa María Ostuma", pais_origens_id: 1},
  {description: "Santiago Nonualco", pais_origens_id: 1},
  {description: "Tapalhuaca", pais_origens_id: 1},
  {description: "Cinquera", pais_origens_id: 1},
  {description: "Dolores", pais_origens_id: 1},
  {description: "Guacotecti", pais_origens_id: 1},
  {description: "Ilobasco", pais_origens_id: 1},
  {description: "Jutiapa", pais_origens_id: 1},
  {description: "San Isidro (Cabañas)", pais_origens_id: 1},
  {description: "Sensuntepeque", pais_origens_id: 1},
  {description: "Tejutepeque", pais_origens_id: 1},
  {description: "Victoria", pais_origens_id: 1},
  {description: "Apastepeque", pais_origens_id: 1},
  {description: "Guadalupe", pais_origens_id: 1},
  {description: "San Cayetano Istepeque", pais_origens_id: 1},
  {description: "San Esteban Catarina", pais_origens_id: 1},
  {description: "San Ildefonso", pais_origens_id: 1},
  {description: "San Lorenzo", pais_origens_id: 1},
  {description: "San Sebastián", pais_origens_id: 1},
  {description: "San Vicente", pais_origens_id: 1},
  {description: "Santa Clara", pais_origens_id: 1},
  {description: "Santo Domingo", pais_origens_id: 1},
  {description: "Tecoluca", pais_origens_id: 1},
  {description: "Tepetitán", pais_origens_id: 1},
  {description: "Verapaz", pais_origens_id: 1},
  {description: "Ahuachapán", pais_origens_id: 1},
  {description: "Jujutla", pais_origens_id: 1},
  {description: "Atiquizaya", pais_origens_id: 1},
  {description: "Concepción de Ataco", pais_origens_id: 1},
  {description: "El Refugio", pais_origens_id: 1},
  {description: "Guaymango", pais_origens_id: 1},
  {description: "Apaneca", pais_origens_id: 1},
  {description: "San Francisco Menéndez", pais_origens_id: 1},
  {description: "San Lorenzo", pais_origens_id: 1},
  {description: "San Pedro Puxtla", pais_origens_id: 1},
  {description: "Tacuba", pais_origens_id: 1},
  {description: "Turín", pais_origens_id: 1},
  {description: "Candelaria de la Frontera", pais_origens_id: 1},
  {description: "Chalchuapa", pais_origens_id: 1},
  {description: "Coatepeque", pais_origens_id: 1},
  {description: "El Congo", pais_origens_id: 1},
  {description: "El Porvenir", pais_origens_id: 1},
  {description: "Masahuat", pais_origens_id: 1},
  {description: "Metapán", pais_origens_id: 1},
  {description: "San Antonio Pajonal", pais_origens_id: 1},
  {description: "San Sebastián Salitrillo", pais_origens_id: 1},
  {description: "Santa Ana", pais_origens_id: 1},
  {description: "Santa Rosa Guachipilín", pais_origens_id: 1},
  {description: "Santiago de la Frontera", pais_origens_id: 1},
  {description: "Texistepeque", pais_origens_id: 1},
  {description: "Acajutla", pais_origens_id: 1},
  {description: "Armenia", pais_origens_id: 1},
  {description: "Caluco", pais_origens_id: 1},
  {description: "Cuisnahuat", pais_origens_id: 1},
  {description: "Izalco", pais_origens_id: 1},
  {description: "Juayúa", pais_origens_id: 1},
  {description: "Nahuizalco", pais_origens_id: 1},
  {description: "Nahulingo", pais_origens_id: 1},
  {description: "Salcoatitán", pais_origens_id: 1},
  {description: "San Antonio del Monte", pais_origens_id: 1},
  {description: "San Julián", pais_origens_id: 1},
  {description: "Santa Catarina Masahuat", pais_origens_id: 1},
  {description: "Santa Isabel Ishuatán", pais_origens_id: 1},
  {description: "Santo Domingo de Guzmán", pais_origens_id: 1},
  {description: "Sonsonate", pais_origens_id: 1},
  {description: "Sonzacate", pais_origens_id: 1},
  {description: "Alegría", pais_origens_id: 1},
  {description: "Berlín", pais_origens_id: 1},
  {description: "California", pais_origens_id: 1},
  {description: "Concepción Batres", pais_origens_id: 1},
  {description: "El Triunfo", pais_origens_id: 1},
  {description: "Ereguayquín", pais_origens_id: 1},
  {description: "Estanzuelas", pais_origens_id: 1},
  {description: "Jiquilisco", pais_origens_id: 1},
  {description: "Jucuapa", pais_origens_id: 1},
  {description: "Jucuarán", pais_origens_id: 1},
  {description: "Mercedes Umaña", pais_origens_id: 1},
  {description: "Nueva Granada", pais_origens_id: 1},
  {description: "Ozatlán", pais_origens_id: 1},
  {description: "Puerto El Triunfo", pais_origens_id: 1},
  {description: "San Agustín", pais_origens_id: 1},
  {description: "San Buenaventura", pais_origens_id: 1},
  {description: "San Dionisio", pais_origens_id: 1},
  {description: "San Francisco Javier", pais_origens_id: 1},
  {description: "Santa Elena", pais_origens_id: 1},
  {description: "Santa María", pais_origens_id: 1},
  {description: "Santiago de María", pais_origens_id: 1},
  {description: "Tecapán", pais_origens_id: 1},
  {description: "Usulután", pais_origens_id: 1},
  {description: "Carolina", pais_origens_id: 1},
  {description: "Chapeltique", pais_origens_id: 1},
  {description: "Chinameca", pais_origens_id: 1},
  {description: "Chirilagua", pais_origens_id: 1},
  {description: "Ciudad Barrios", pais_origens_id: 1},
  {description: "Comacarán", pais_origens_id: 1},
  {description: "El Tránsito", pais_origens_id: 1},
  {description: "Lolotique", pais_origens_id: 1},
  {description: "Moncagua", pais_origens_id: 1},
  {description: "Nueva Guadalupe", pais_origens_id: 1},
  {description: "Nuevo Edén de San Juan", pais_origens_id: 1},
  {description: "Quelepa", pais_origens_id: 1},
  {description: "San Antonio del Mosco", pais_origens_id: 1},
  {description: "San Gerardo", pais_origens_id: 1},
  {description: "San Jorge", pais_origens_id: 1},
  {description: "San Luis de la Reina", pais_origens_id: 1},
  {description: "San Miguel", pais_origens_id: 1},
  {description: "San Rafael Oriente", pais_origens_id: 1},
  {description: "Sesori", pais_origens_id: 1},
  {description: "Uluazapa", pais_origens_id: 1},
  {description: "Arambala", pais_origens_id: 1},
  {description: "Cacaopera", pais_origens_id: 1},
  {description: "Chilanga", pais_origens_id: 1},
  {description: "Corinto", pais_origens_id: 1},
  {description: "Delicias de Concepción", pais_origens_id: 1},
  {description: "El Divisadero", pais_origens_id: 1},
  {description: "El Rosario (Morazán)", pais_origens_id: 1},
  {description: "Gualococti", pais_origens_id: 1},
  {description: "Guatajiagua", pais_origens_id: 1},
  {description: "Joateca", pais_origens_id: 1},
  {description: "Jocoaitique", pais_origens_id: 1},
  {description: "Jocoro", pais_origens_id: 1},
  {description: "Lolotiquillo", pais_origens_id: 1},
  {description: "Meanguera", pais_origens_id: 1},
  {description: "Osicala", pais_origens_id: 1},
  {description: "Perquín", pais_origens_id: 1},
  {description: "San Carlos", pais_origens_id: 1},
  {description: "San Fernando (Morazán)", pais_origens_id: 1},
  {description: "San Francisco Gotera", pais_origens_id: 1},
  {description: "San Isidro (Morazán)", pais_origens_id: 1},
  {description: "San Simón", pais_origens_id: 1},
  {description: "Sensembra", pais_origens_id: 1},
  {description: "Sociedad", pais_origens_id: 1},
  {description: "Torola", pais_origens_id: 1},
  {description: "Yamabal", pais_origens_id: 1},
  {description: "Yoloaiquín", pais_origens_id: 1},
  {description: "La Unión", pais_origens_id: 1},
  {description: "San Alejo", pais_origens_id: 1},
  {description: "Yucuaiquín", pais_origens_id: 1},
  {description: "Conchagua", pais_origens_id: 1},
  {description: "Intipucá", pais_origens_id: 1},
  {description: "San José", pais_origens_id: 1},
  {description: "El Carmen (La Unión)", pais_origens_id: 1},
  {description: "Yayantique", pais_origens_id: 1},
  {description: "Bolívar", pais_origens_id: 1},
  {description: "Meanguera del Golfo", pais_origens_id: 1},
  {description: "Santa Rosa de Lima", pais_origens_id: 1},
  {description: "Pasaquina", pais_origens_id: 1},
  {description: "Anamoros", pais_origens_id: 1},
  {description: "Nueva Esparta", pais_origens_id: 1},
  {description: "El Sauce", pais_origens_id: 1},
  {description: "Concepción de Oriente", pais_origens_id: 1},
  {description: "Polorós", pais_origens_id: 1},
  {description: "Lislique", pais_origens_id: 1},
  {description: "Antiguo Cuscatlán", pais_origens_id: 1},
  {description: "Chiltiupán", pais_origens_id: 1},
  {description: "Ciudad Arce", pais_origens_id: 1},
  {description: "Colón", pais_origens_id: 1},
  {description: "Comasagua", pais_origens_id: 1},
  {description: "Huizúcar", pais_origens_id: 1},
  {description: "Jayaque", pais_origens_id: 1},
  {description: "Jicalapa", pais_origens_id: 1},
  {description: "La Libertad", pais_origens_id: 1},
  {description: "Santa Tecla", pais_origens_id: 1},
  {description: "Nuevo Cuscatlán", pais_origens_id: 1},
  {description: "San Juan Opico", pais_origens_id: 1},
  {description: "Quezaltepeque", pais_origens_id: 1},
  {description: "Sacacoyo", pais_origens_id: 1},
  {description: "San José Villanueva", pais_origens_id: 1},
  {description: "San Matías", pais_origens_id: 1},
  {description: "San Pablo Tacachico", pais_origens_id: 1},
  {description: "Talnique", pais_origens_id: 1},
  {description: "Tamanique", pais_origens_id: 1},
  {description: "Teotepeque", pais_origens_id: 1},
  {description: "Tepecoyo", pais_origens_id: 1},
  {description: "Zaragoza", pais_origens_id: 1},
  {description: "Agua Caliente", pais_origens_id: 1},
  {description: "Arcatao", pais_origens_id: 1},
  {description: "Azacualpa", pais_origens_id: 1},
  {description: "Cancasque", pais_origens_id: 1},
  {description: "Chalatenango", pais_origens_id: 1},
  {description: "Citalá", pais_origens_id: 1},
  {description: "Comapala", pais_origens_id: 1},
  {description: "Concepción Quezaltepeque", pais_origens_id: 1},
  {description: "Dulce Nombre de María", pais_origens_id: 1},
  {description: "El Carrizal", pais_origens_id: 1},
  {description: "El Paraíso", pais_origens_id: 1},
  {description: "La Laguna", pais_origens_id: 1},
  {description: "La Palma", pais_origens_id: 1},
  {description: "La Reina", pais_origens_id: 1},
  {description: "Las Vueltas", pais_origens_id: 1},
  {description: "Nueva Concepción", pais_origens_id: 1},
  {description: "Nueva Trinidad", pais_origens_id: 1},
  {description: "Nombre de Jesús", pais_origens_id: 1},
  {description: "Ojos de Agua", pais_origens_id: 1},
  {description: "Potonico", pais_origens_id: 1},
  {description: "San Antonio de la Cruz", pais_origens_id: 1},
  {description: "San Antonio Los Ranchos", pais_origens_id: 1},
  {description: "San Fernando (Chalatenango)", pais_origens_id: 1},
  {description: "San Francisco Lempa", pais_origens_id: 1},
  {description: "San Francisco Morazán", pais_origens_id: 1},
  {description: "San Ignacio", pais_origens_id: 1},
  {description: "San Isidro Labrador", pais_origens_id: 1},
  {description: "Las Flores", pais_origens_id: 1},
  {description: "San Luis del Carmen", pais_origens_id: 1},
  {description: "San Miguel de Mercedes", pais_origens_id: 1},
  {description: "San Rafael", pais_origens_id: 1},
  {description: "Santa Rita", pais_origens_id: 1},
  {description: "Tejutla", pais_origens_id: 1},
  {description: "Cojutepeque", pais_origens_id: 1},
  {description: "Candelaria", pais_origens_id: 1},
  {description: "El Carmen (Cuscatlán)", pais_origens_id: 1},
  {description: "El Rosario (Cuscatlán)", pais_origens_id: 1},
  {description: "Monte San Juan", pais_origens_id: 1},
  {description: "Oratorio de Concepción", pais_origens_id: 1},
  {description: "San Bartolomé Perulapía", pais_origens_id: 1},
  {description: "San Cristóbal", pais_origens_id: 1},
  {description: "San José Guayabal", pais_origens_id: 1},
  {description: "San Pedro Perulapán", pais_origens_id: 1},
  {description: "San Rafael Cedros", pais_origens_id: 1},
  {description: "San Ramón", pais_origens_id: 1},
  {description: "Santa Cruz Analquito", pais_origens_id: 1},
  {description: "Santa Cruz Michapa", pais_origens_id: 1},
  {description: "Suchitoto", pais_origens_id: 1},
  {description: "Tenancingo", pais_origens_id: 1},
  {description: "Aguilares", pais_origens_id: 1},
  {description: "Apopa", pais_origens_id: 1},
  {description: "Ayutuxtepeque", pais_origens_id: 1},
  {description: "Cuscatancingo", pais_origens_id: 1},
  {description: "Ciudad Delgado", pais_origens_id: 1},
  {description: "El Paisnal", pais_origens_id: 1},
  {description: "Guazapa", pais_origens_id: 1},
  {description: "Ilopango", pais_origens_id: 1},
  {description: "Mejicanos", pais_origens_id: 1},
  {description: "Ahuachapán", pais_origens_id: 1},
  {description: "Jujutla", pais_origens_id: 1},
  {description: "Atiquizaya", pais_origens_id: 1},
  {description: "Concepción de Ataco", pais_origens_id: 1},
  {description: "El Refugio", pais_origens_id: 1},
  {description: "Guaymango", pais_origens_id: 1},
  {description: "Apaneca", pais_origens_id: 1},
  {description: "San Francisco Menéndez", pais_origens_id: 1},
  {description: "San Lorenzo", pais_origens_id: 1},
  {description: "San Pedro Puxtla", pais_origens_id: 1},
  {description: "Tacuba", pais_origens_id: 1},
  {description: "Turín", pais_origens_id: 1},
  {description: "Candelaria de la Frontera", pais_origens_id: 1},
  {description: "Chalchuapa", pais_origens_id: 1},
  {description: "Coatepeque", pais_origens_id: 1},
  {description: "El Congo", pais_origens_id: 1},
  {description: "El Porvenir", pais_origens_id: 1},
  {description: "Masahuat", pais_origens_id: 1},
  {description: "Metapán", pais_origens_id: 1},
  {description: "San Antonio Pajonal", pais_origens_id: 1},
  {description: "San Sebastián Salitrillo", pais_origens_id: 1},
  {description: "Santa Ana", pais_origens_id: 1},
  {description: "Santa Rosa Guachipilín", pais_origens_id: 1},
  {description: "Santiago de la Frontera", pais_origens_id: 1},
  {description: "Texistepeque", pais_origens_id: 1},
  {description: "Acajutla", pais_origens_id: 1},
  {description: "Armenia", pais_origens_id: 1},
  {description: "Caluco", pais_origens_id: 1},
  {description: "Cuisnahuat", pais_origens_id: 1},
  {description: "Izalco", pais_origens_id: 1},
  {description: "Juayúa", pais_origens_id: 1},
  {description: "Nahuizalco", pais_origens_id: 1},
  {description: "Nahulingo", pais_origens_id: 1},
  {description: "Salcoatitán", pais_origens_id: 1},
  {description: "San Antonio del Monte", pais_origens_id: 1},
  {description: "San Julián", pais_origens_id: 1},
  {description: "Santa Catarina Masahuat", pais_origens_id: 1},
  {description: "Santa Isabel Ishuatán", pais_origens_id: 1},
  {description: "Santo Domingo de Guzmán", pais_origens_id: 1},
  {description: "Sonsonate", pais_origens_id: 1},
  {description: "Sonzacate", pais_origens_id: 1},
  {description: "Alegría", pais_origens_id: 1},
  {description: "Berlín", pais_origens_id: 1},
  {description: "California", pais_origens_id: 1},
  {description: "Concepción Batres", pais_origens_id: 1},
  {description: "El Triunfo", pais_origens_id: 1},
  {description: "Ereguayquín", pais_origens_id: 1},
  {description: "Estanzuelas", pais_origens_id: 1},
  {description: "Jiquilisco", pais_origens_id: 1},
  {description: "Jucuapa", pais_origens_id: 1},
  {description: "Jucuarán", pais_origens_id: 1},
  {description: "Mercedes Umaña", pais_origens_id: 1},
  {description: "Nueva Granada", pais_origens_id: 1},
  {description: "Ozatlán", pais_origens_id: 1},
  {description: "Puerto El Triunfo", pais_origens_id: 1},
  {description: "San Agustín", pais_origens_id: 1},
  {description: "San Buenaventura", pais_origens_id: 1},
  {description: "San Dionisio", pais_origens_id: 1},
  {description: "San Francisco Javier", pais_origens_id: 1},
  {description: "Santa Elena", pais_origens_id: 1},
  {description: "Santa María", pais_origens_id: 1},
  {description: "Santiago de María", pais_origens_id: 1},
  {description: "Tecapán", pais_origens_id: 1},
  {description: "Usulután", pais_origens_id: 1},
  {description: "Carolina", pais_origens_id: 1},
  {description: "Chapeltique", pais_origens_id: 1},
  {description: "Chinameca", pais_origens_id: 1},
  {description: "Chirilagua", pais_origens_id: 1},
  {description: "Ciudad Barrios", pais_origens_id: 1},
  {description: "Comacarán", pais_origens_id: 1},
  {description: "El Tránsito", pais_origens_id: 1},
  {description: "Lolotique", pais_origens_id: 1},
  {description: "Moncagua", pais_origens_id: 1},
  {description: "Nueva Guadalupe", pais_origens_id: 1},
  {description: "Nuevo Edén de San Juan", pais_origens_id: 1},
  {description: "Quelepa", pais_origens_id: 1},
  {description: "San Antonio del Mosco", pais_origens_id: 1},
  {description: "San Gerardo", pais_origens_id: 1},
  {description: "San Jorge", pais_origens_id: 1},
  {description: "San Luis de la Reina", pais_origens_id: 1},
  {description: "San Miguel", pais_origens_id: 1},
  {description: "San Rafael Oriente", pais_origens_id: 1},
  {description: "Sesori", pais_origens_id: 1},
  {description: "Uluazapa", pais_origens_id: 1},
  {description: "Arambala", pais_origens_id: 1},
  {description: "Cacaopera", pais_origens_id: 1},
  {description: "Chilanga", pais_origens_id: 1},
  {description: "Corinto", pais_origens_id: 1},
  {description: "Delicias de Concepción", pais_origens_id: 1},
  {description: "El Divisadero", pais_origens_id: 1},
  {description: "El Rosario (Morazán)", pais_origens_id: 1},
  {description: "Gualococti", pais_origens_id: 1},
  {description: "Guatajiagua", pais_origens_id: 1},
  {description: "Joateca", pais_origens_id: 1},
  {description: "Jocoaitique", pais_origens_id: 1},
  {description: "Jocoro", pais_origens_id: 1},
  {description: "Lolotiquillo", pais_origens_id: 1},
  {description: "Meanguera", pais_origens_id: 1},
  {description: "Osicala", pais_origens_id: 1},
  {description: "Perquín", pais_origens_id: 1},
  {description: "San Carlos", pais_origens_id: 1},
  {description: "San Fernando (Morazán)", pais_origens_id: 1},
  {description: "San Francisco Gotera", pais_origens_id: 1},
  {description: "San Isidro (Morazán)", pais_origens_id: 1},
  {description: "San Simón", pais_origens_id: 1},
  {description: "Sensembra", pais_origens_id: 1},
  {description: "Sociedad", pais_origens_id: 1},
  {description: "Torola", pais_origens_id: 1},
  {description: "Yamabal", pais_origens_id: 1},
  {description: "Yoloaiquín", pais_origens_id: 1},
  {description: "La Unión", pais_origens_id: 1},
  {description: "San Alejo", pais_origens_id: 1},
  {description: "Yucuaiquín", pais_origens_id: 1},
  {description: "Conchagua", pais_origens_id: 1},
  {description: "Intipucá", pais_origens_id: 1},
  {description: "San José", pais_origens_id: 1},
  {description: "El Carmen (La Unión)", pais_origens_id: 1},
  {description: "Yayantique", pais_origens_id: 1},
  {description: "Bolívar", pais_origens_id: 1},
  {description: "Meanguera del Golfo", pais_origens_id: 1},
  {description: "Santa Rosa de Lima", pais_origens_id: 1},
  {description: "Pasaquina", pais_origens_id: 1},
  {description: "Anamoros", pais_origens_id: 1},
  {description: "Nueva Esparta", pais_origens_id: 1},
  {description: "El Sauce", pais_origens_id: 1},
  {description: "Concepción de Oriente", pais_origens_id: 1},
  {description: "Polorós", pais_origens_id: 1},
  {description: "Lislique", pais_origens_id: 1},
  {description: "Antiguo Cuscatlán", pais_origens_id: 1},
  {description: "Chiltiupán", pais_origens_id: 1},
  {description: "Ciudad Arce", pais_origens_id: 1},
  {description: "Colón", pais_origens_id: 1},
  {description: "Comasagua", pais_origens_id: 1},
  {description: "Huizúcar", pais_origens_id: 1},
  {description: "Jayaque", pais_origens_id: 1},
  {description: "Jicalapa", pais_origens_id: 1},
  {description: "La Libertad", pais_origens_id: 1},
  {description: "Santa Tecla", pais_origens_id: 1},
  {description: "Nuevo Cuscatlán", pais_origens_id: 1},
  {description: "San Juan Opico", pais_origens_id: 1},
  {description: "Quezaltepeque", pais_origens_id: 1},
  {description: "Sacacoyo", pais_origens_id: 1},
  {description: "San José Villanueva", pais_origens_id: 1},
  {description: "San Matías", pais_origens_id: 1},
  {description: "San Pablo Tacachico", pais_origens_id: 1},
  {description: "Talnique", pais_origens_id: 1},
  {description: "Tamanique", pais_origens_id: 1},
  {description: "Teotepeque", pais_origens_id: 1},
  {description: "Tepecoyo", pais_origens_id: 1},
  {description: "Zaragoza", pais_origens_id: 1},
  {description: "Agua Caliente", pais_origens_id: 1},
  {description: "Arcatao", pais_origens_id: 1},
  {description: "Azacualpa", pais_origens_id: 1},
  {description: "Cancasque", pais_origens_id: 1},
  {description: "Chalatenango", pais_origens_id: 1},
  {description: "Citalá", pais_origens_id: 1},
  {description: "Comapala", pais_origens_id: 1},
  {description: "Concepción Quezaltepeque", pais_origens_id: 1},
  {description: "Dulce Nombre de María", pais_origens_id: 1},
  {description: "El Carrizal", pais_origens_id: 1},
  {description: "El Paraíso", pais_origens_id: 1},
  {description: "La Laguna", pais_origens_id: 1},
  {description: "La Palma", pais_origens_id: 1},
  {description: "La Reina", pais_origens_id: 1},
  {description: "Las Vueltas", pais_origens_id: 1},
  {description: "Nueva Concepción", pais_origens_id: 1},
  {description: "Nueva Trinidad", pais_origens_id: 1},
  {description: "Nombre de Jesús", pais_origens_id: 1},
  {description: "Ojos de Agua", pais_origens_id: 1},
  {description: "Potonico", pais_origens_id: 1},
  {description: "San Antonio de la Cruz", pais_origens_id: 1},
  {description: "San Antonio Los Ranchos", pais_origens_id: 1},
  {description: "San Fernando (Chalatenango)", pais_origens_id: 1},
  {description: "San Francisco Lempa", pais_origens_id: 1},
  {description: "San Francisco Morazán", pais_origens_id: 1},
  {description: "San Ignacio", pais_origens_id: 1},
  {description: "San Isidro Labrador", pais_origens_id: 1},
  {description: "Las Flores", pais_origens_id: 1},
  {description: "San Luis del Carmen", pais_origens_id: 1},
  {description: "San Miguel de Mercedes", pais_origens_id: 1},
  {description: "San Rafael", pais_origens_id: 1},
  {description: "Santa Rita", pais_origens_id: 1},
  {description: "Tejutla", pais_origens_id: 1},
  {description: "Cojutepeque", pais_origens_id: 1},
  {description: "Candelaria", pais_origens_id: 1},
  {description: "El Carmen (Cuscatlán)", pais_origens_id: 1},
  {description: "El Rosario (Cuscatlán)", pais_origens_id: 1},
  {description: "Monte San Juan", pais_origens_id: 1},
  {description: "Oratorio de Concepción", pais_origens_id: 1},
  {description: "San Bartolomé Perulapía", pais_origens_id: 1},
  {description: "San Cristóbal", pais_origens_id: 1},
  {description: "San José Guayabal", pais_origens_id: 1},
  {description: "San Pedro Perulapán", pais_origens_id: 1},
  {description: "San Rafael Cedros", pais_origens_id: 1},
  {description: "San Ramón", pais_origens_id: 1},
  {description: "Santa Cruz Analquito", pais_origens_id: 1},
  {description: "Santa Cruz Michapa", pais_origens_id: 1},
  {description: "Suchitoto", pais_origens_id: 1},
  {description: "Tenancingo", pais_origens_id: 1},
  {description: "Aguilares", pais_origens_id: 1},
  {description: "Apopa", pais_origens_id: 1},
  {description: "Ayutuxtepeque", pais_origens_id: 1},
  {description: "Cuscatancingo", pais_origens_id: 1},
  {description: "Ciudad Delgado", pais_origens_id: 1},
  {description: "El Paisnal", pais_origens_id: 1},
  {description: "Guazapa", pais_origens_id: 1},
  {description: "Ilopango", pais_origens_id: 1},
  {description: "Mejicanos", pais_origens_id: 1},
  {description: "Nejapa", pais_origens_id: 1},
  {description: "Panchimalco", pais_origens_id: 1},
  {description: "Rosario de Mora", pais_origens_id: 1},
  {description: "San Marcos", pais_origens_id: 1},
  {description: "San Martín", pais_origens_id: 1},
  {description: "San Salvador", pais_origens_id: 1},
  {description: "Santiago Texacuangos", pais_origens_id: 1},
  {description: "Santo Tomás", pais_origens_id: 1},
  {description: "Soyapango", pais_origens_id: 1},
  {description: "Tonacatepeque", pais_origens_id: 1},
  {description: "Zacatecoluca", pais_origens_id: 1},
  {description: "Cuyultitán", pais_origens_id: 1},
  {description: "El Rosario (La Paz)", pais_origens_id: 1},
  {description: "Jerusalén", pais_origens_id: 1},
  {description: "Mercedes La Ceiba", pais_origens_id: 1},
  {description: "Olocuilta", pais_origens_id: 1},
  {description: "Paraíso de Osorio", pais_origens_id: 1},
  {description: "San Antonio Masahuat", pais_origens_id: 1},
  {description: "San Emigdio", pais_origens_id: 1},
  {description: "San Francisco Chinameca", pais_origens_id: 1},
  {description: "San Pedro Masahuat", pais_origens_id: 1},
  {description: "San Juan Nonualco", pais_origens_id: 1},
  {description: "San Juan Talpa", pais_origens_id: 1},
  {description: "San Juan Tepezontes", pais_origens_id: 1},
  {description: "San Luis La Herradura", pais_origens_id: 1},
  {description: "San Luis Talpa", pais_origens_id: 1},
  {description: "San Miguel Tepezontes", pais_origens_id: 1},
  {description: "San Pedro Nonualco", pais_origens_id: 1},
  {description: "San Rafael Obrajuelo", pais_origens_id: 1},
  {description: "Santa María Ostuma", pais_origens_id: 1},
  {description: "Santiago Nonualco", pais_origens_id: 1},
  {description: "Tapalhuaca", pais_origens_id: 1},
  {description: "Cinquera", pais_origens_id: 1},
  {description: "Dolores", pais_origens_id: 1},
  {description: "Guacotecti", pais_origens_id: 1},
  {description: "Ilobasco", pais_origens_id: 1},
  {description: "Jutiapa", pais_origens_id: 1},
  {description: "San Isidro (Cabañas)", pais_origens_id: 1},
  {description: "Sensuntepeque", pais_origens_id: 1},
  {description: "Tejutepeque", pais_origens_id: 1},
  {description: "Victoria", pais_origens_id: 1},
  {description: "Apastepeque", pais_origens_id: 1},
  {description: "Guadalupe", pais_origens_id: 1},
  {description: "San Cayetano Istepeque", pais_origens_id: 1},
  {description: "San Esteban Catarina", pais_origens_id: 1},
  {description: "San Ildefonso", pais_origens_id: 1},
  {description: "San Lorenzo", pais_origens_id: 1},
  {description: "San Sebastián", pais_origens_id: 1},
  {description: "San Vicente", pais_origens_id: 1},
  {description: "Santa Clara", pais_origens_id: 1},
  {description: "Santo Domingo", pais_origens_id: 1},
  {description: "Tecoluca", pais_origens_id: 1},
  {description: "Tepetitán", pais_origens_id: 1},
  {description: "Verapaz", pais_origens_id: 1},
  {description: "La Unión", pais_origens_id: 1},
  {description: "San Alejo", pais_origens_id: 1},
  {description: "Yucuaiquín", pais_origens_id: 1},
  {description: "Conchagua", pais_origens_id: 1},
  {description: "Intipucá", pais_origens_id: 1},
  {description: "San José", pais_origens_id: 1},
  {description: "El Carmen (La Unión)", pais_origens_id: 1},
  {description: "Yayantique", pais_origens_id: 1},
  {description: "Bolívar", pais_origens_id: 1},
  {description: "Meanguera del Golfo", pais_origens_id: 1},
  {description: "Santa Rosa de Lima", pais_origens_id: 1},
  {description: "Pasaquina", pais_origens_id: 1},
  {description: "Anamoros", pais_origens_id: 1},
  {description: "Nueva Esparta", pais_origens_id: 1},
  {description: "El Sauce", pais_origens_id: 1},
  {description: "Concepción de Oriente", pais_origens_id: 1},
  {description: "Polorós", pais_origens_id: 1},
  {description: "Lislique", pais_origens_id: 1},
  {description: "Antiguo Cuscatlán", pais_origens_id: 1},
  {description: "Chiltiupán", pais_origens_id: 1},
  {description: "Ciudad Arce", pais_origens_id: 1},
  {description: "Colón", pais_origens_id: 1},
  {description: "Comasagua", pais_origens_id: 1},
  {description: "Huizúcar", pais_origens_id: 1},
  {description: "Jayaque", pais_origens_id: 1},
  {description: "Jicalapa", pais_origens_id: 1},
  {description: "La Libertad", pais_origens_id: 1},
  {description: "Santa Tecla", pais_origens_id: 1},
  {description: "Nuevo Cuscatlán", pais_origens_id: 1},
  {description: "San Juan Opico", pais_origens_id: 1},
  {description: "Quezaltepeque", pais_origens_id: 1},
  {description: "Sacacoyo", pais_origens_id: 1},
  {description: "San José Villanueva", pais_origens_id: 1},
  {description: "San Matías", pais_origens_id: 1},
  {description: "San Pablo Tacachico", pais_origens_id: 1},
  {description: "Talnique", pais_origens_id: 1},
  {description: "Tamanique", pais_origens_id: 1},
  {description: "Teotepeque", pais_origens_id: 1},
  {description: "Tepecoyo", pais_origens_id: 1},
  {description: "Zaragoza", pais_origens_id: 1},
  {description: "Agua Caliente", pais_origens_id: 1},
  {description: "Arcatao", pais_origens_id: 1},
  {description: "Azacualpa", pais_origens_id: 1},
  {description: "Cancasque", pais_origens_id: 1},
  {description: "Chalatenango", pais_origens_id: 1},
  {description: "Citalá", pais_origens_id: 1},
  {description: "Comapala", pais_origens_id: 1},
  {description: "Concepción Quezaltepeque", pais_origens_id: 1},
  {description: "Dulce Nombre de María", pais_origens_id: 1},
  {description: "El Carrizal", pais_origens_id: 1},
  {description: "El Paraíso", pais_origens_id: 1},
  {description: "La Laguna", pais_origens_id: 1},
  {description: "La Palma", pais_origens_id: 1},
  {description: "La Reina", pais_origens_id: 1},
  {description: "Las Vueltas", pais_origens_id: 1},
  {description: "Nueva Concepción", pais_origens_id: 1},
  {description: "Nueva Trinidad", pais_origens_id: 1},
  {description: "Nombre de Jesús", pais_origens_id: 1},
  {description: "Ojos de Agua", pais_origens_id: 1},
  {description: "Potonico", pais_origens_id: 1},
  {description: "San Antonio de la Cruz", pais_origens_id: 1},
  {description: "San Antonio Los Ranchos", pais_origens_id: 1},
  {description: "San Fernando (Chalatenango)", pais_origens_id: 1},
  {description: "San Francisco Lempa", pais_origens_id: 1},
  {description: "San Francisco Morazán", pais_origens_id: 1},
  {description: "San Ignacio", pais_origens_id: 1},
  {description: "San Isidro Labrador", pais_origens_id: 1},
  {description: "Las Flores", pais_origens_id: 1},
  {description: "San Luis del Carmen", pais_origens_id: 1},
  {description: "San Miguel de Mercedes", pais_origens_id: 1},
  {description: "San Rafael", pais_origens_id: 1},
  {description: "Santa Rita", pais_origens_id: 1},
  {description: "Tejutla", pais_origens_id: 1},
  {description: "Cojutepeque", pais_origens_id: 1},
  {description: "Candelaria", pais_origens_id: 1},
  {description: "El Carmen (Cuscatlán)", pais_origens_id: 1},
  {description: "El Rosario (Cuscatlán)", pais_origens_id: 1},
  {description: "Monte San Juan", pais_origens_id: 1},
  {description: "Oratorio de Concepción", pais_origens_id: 1},
  {description: "San Bartolomé Perulapía", pais_origens_id: 1},
  {description: "San Cristóbal", pais_origens_id: 1},
  {description: "San José Guayabal", pais_origens_id: 1},
  {description: "San Pedro Perulapán", pais_origens_id: 1},
  {description: "San Rafael Cedros", pais_origens_id: 1},
  {description: "San Ramón", pais_origens_id: 1},
  {description: "Santa Cruz Analquito", pais_origens_id: 1},
  {description: "Santa Cruz Michapa", pais_origens_id: 1},
  {description: "Suchitoto", pais_origens_id: 1},
  {description: "Tenancingo", pais_origens_id: 1},
  {description: "Aguilares", pais_origens_id: 1},
  {description: "Apopa", pais_origens_id: 1},
  {description: "Ayutuxtepeque", pais_origens_id: 1},
  {description: "Cuscatancingo", pais_origens_id: 1},
  {description: "Ciudad Delgado", pais_origens_id: 1},
  {description: "El Paisnal", pais_origens_id: 1},
  {description: "Guazapa", pais_origens_id: 1},
  {description: "Ilopango", pais_origens_id: 1},
  {description: "Mejicanos", pais_origens_id: 1},
  {description: "Nejapa", pais_origens_id: 1},
  {description: "Panchimalco", pais_origens_id: 1},
  {description: "Rosario de Mora", pais_origens_id: 1},
  {description: "San Marcos", pais_origens_id: 1},
  {description: "San Martín", pais_origens_id: 1},
  {description: "San Salvador", pais_origens_id: 1},
  {description: "Santiago Texacuangos", pais_origens_id: 1},
  {description: "Santo Tomás", pais_origens_id: 1},
  {description: "Soyapango", pais_origens_id: 1},
  {description: "Tonacatepeque", pais_origens_id: 1},
  {description: "Zacatecoluca", pais_origens_id: 1},
  {description: "Cuyultitán", pais_origens_id: 1},
  {description: "El Rosario (La Paz)", pais_origens_id: 1},
  {description: "Jerusalén", pais_origens_id: 1},
  {description: "Mercedes La Ceiba", pais_origens_id: 1},
  {description: "Olocuilta", pais_origens_id: 1},
  {description: "Paraíso de Osorio", pais_origens_id: 1},
  {description: "San Antonio Masahuat", pais_origens_id: 1},
  {description: "San Emigdio", pais_origens_id: 1},
  {description: "San Francisco Chinameca", pais_origens_id: 1},
  {description: "San Pedro Masahuat", pais_origens_id: 1},
  {description: "San Juan Nonualco", pais_origens_id: 1},
  {description: "San Juan Talpa", pais_origens_id: 1},
  {description: "San Juan Tepezontes", pais_origens_id: 1},
  {description: "San Luis La Herradura", pais_origens_id: 1},
  {description: "San Luis Talpa", pais_origens_id: 1},
  {description: "San Miguel Tepezontes", pais_origens_id: 1},
  {description: "San Pedro Nonualco", pais_origens_id: 1},
  {description: "San Rafael Obrajuelo", pais_origens_id: 1},
  {description: "Santa María Ostuma", pais_origens_id: 1},
  {description: "Santiago Nonualco", pais_origens_id: 1},
  {description: "Tapalhuaca", pais_origens_id: 1},
  {description: "Cinquera", pais_origens_id: 1},
  {description: "Dolores", pais_origens_id: 1},
  {description: "Guacotecti", pais_origens_id: 1},
  {description: "Ilobasco", pais_origens_id: 1},
  {description: "Jutiapa", pais_origens_id: 1},
  {description: "San Isidro (Cabañas)", pais_origens_id: 1},
  {description: "Sensuntepeque", pais_origens_id: 1},
  {description: "Tejutepeque", pais_origens_id: 1},
  {description: "Victoria", pais_origens_id: 1},
  {description: "Apastepeque", pais_origens_id: 1},
  {description: "Guadalupe", pais_origens_id: 1},
  {description: "San Cayetano Istepeque", pais_origens_id: 1},
  {description: "San Esteban Catarina", pais_origens_id: 1},
  {description: "San Ildefonso", pais_origens_id: 1},
  {description: "San Lorenzo", pais_origens_id: 1},
  {description: "San Sebastián", pais_origens_id: 1},
  {description: "San Vicente", pais_origens_id: 1},
  {description: "Santa Clara", pais_origens_id: 1},
  {description: "Santo Domingo", pais_origens_id: 1},
  {description: "Tecoluca", pais_origens_id: 1},
  {description: "Tepetitán", pais_origens_id: 1},
  {description: "Verapaz", pais_origens_id: 1},
  {description: "Zacatecoluca", pais_origens_id: 1},
  {description: "Cuyultitán", pais_origens_id: 1},
  {description: "El Rosario (La Paz)", pais_origens_id: 1},
  {description: "Jerusalén", pais_origens_id: 1},
  {description: "Mercedes La Ceiba", pais_origens_id: 1},
  {description: "Olocuilta", pais_origens_id: 1},
  {description: "Paraíso de Osorio", pais_origens_id: 1},
  {description: "San Antonio Masahuat", pais_origens_id: 1},
  {description: "San Emigdio", pais_origens_id: 1},
  {description: "San Francisco Chinameca", pais_origens_id: 1},
  {description: "San Pedro Masahuat", pais_origens_id: 1},
  {description: "San Juan Nonualco", pais_origens_id: 1},
  {description: "San Juan Talpa", pais_origens_id: 1},
  {description: "San Juan Tepezontes", pais_origens_id: 1},
  {description: "San Luis La Herradura", pais_origens_id: 1},
  {description: "San Luis Talpa", pais_origens_id: 1},
  {description: "San Miguel Tepezontes", pais_origens_id: 1},
  {description: "San Pedro Nonualco", pais_origens_id: 1},
  {description: "San Rafael Obrajuelo", pais_origens_id: 1},
  {description: "Santa María Ostuma", pais_origens_id: 1},
  {description: "Santiago Nonualco", pais_origens_id: 1},
  {description: "Tapalhuaca", pais_origens_id: 1},
  {description: "Cinquera", pais_origens_id: 1},
  {description: "Dolores", pais_origens_id: 1},
  {description: "Guacotecti", pais_origens_id: 1},
  {description: "Ilobasco", pais_origens_id: 1},
  {description: "Jutiapa", pais_origens_id: 1},
  {description: "San Isidro (Cabañas)", pais_origens_id: 1},
  {description: "Sensuntepeque", pais_origens_id: 1},
  {description: "Tejutepeque", pais_origens_id: 1},
  {description: "Victoria", pais_origens_id: 1},
  {description: "Apastepeque", pais_origens_id: 1},
  {description: "Guadalupe", pais_origens_id: 1},
  {description: "San Cayetano Istepeque", pais_origens_id: 1},
  {description: "San Esteban Catarina", pais_origens_id: 1},
  {description: "San Ildefonso", pais_origens_id: 1},
  {description: "San Lorenzo", pais_origens_id: 1},
  {description: "San Sebastián", pais_origens_id: 1},
  {description: "San Vicente", pais_origens_id: 1},
  {description: "Santa Clara", pais_origens_id: 1},
  {description: "Santo Domingo", pais_origens_id: 1},
  {description: "Tecoluca", pais_origens_id: 1},
  {description: "Tepetitán", pais_origens_id: 1},
  {description: "Verapaz", pais_origens_id: 1},
  {description: "Nejapa", pais_origens_id: 1},
  {description: "Panchimalco", pais_origens_id: 1},
  {description: "Rosario de Mora", pais_origens_id: 1},
  {description: "San Marcos", pais_origens_id: 1},
  {description: "San Martín", pais_origens_id: 1},
  {description: "San Salvador", pais_origens_id: 1},
  {description: "Santiago Texacuangos", pais_origens_id: 1},
  {description: "Santo Tomás", pais_origens_id: 1},
  {description: "Soyapango", pais_origens_id: 1},
  {description: "Tonacatepeque", pais_origens_id: 1},
  {description: "Zacatecoluca", pais_origens_id: 1},
  {description: "Cuyultitán", pais_origens_id: 1},
  {description: "El Rosario (La Paz)", pais_origens_id: 1},
  {description: "Jerusalén", pais_origens_id: 1},
  {description: "Mercedes La Ceiba", pais_origens_id: 1},
  {description: "Olocuilta", pais_origens_id: 1},
  {description: "Paraíso de Osorio", pais_origens_id: 1},
  {description: "San Antonio Masahuat", pais_origens_id: 1},
  {description: "San Emigdio", pais_origens_id: 1},
  {description: "San Francisco Chinameca", pais_origens_id: 1},
  {description: "San Pedro Masahuat", pais_origens_id: 1},
  {description: "San Juan Nonualco", pais_origens_id: 1},
  {description: "San Juan Talpa", pais_origens_id: 1},
  {description: "San Juan Tepezontes", pais_origens_id: 1},
  {description: "San Luis La Herradura", pais_origens_id: 1},
  {description: "San Luis Talpa", pais_origens_id: 1},
  {description: "San Miguel Tepezontes", pais_origens_id: 1},
  {description: "San Pedro Nonualco", pais_origens_id: 1},
  {description: "San Rafael Obrajuelo", pais_origens_id: 1},
  {description: "Santa María Ostuma", pais_origens_id: 1},
  {description: "Santiago Nonualco", pais_origens_id: 1},
  {description: "Tapalhuaca", pais_origens_id: 1},
  {description: "Cinquera", pais_origens_id: 1},
  {description: "Dolores", pais_origens_id: 1},
  {description: "Guacotecti", pais_origens_id: 1},
  {description: "Ilobasco", pais_origens_id: 1},
  {description: "Jutiapa", pais_origens_id: 1},
  {description: "San Isidro (Cabañas)", pais_origens_id: 1},
  {description: "Sensuntepeque", pais_origens_id: 1},
  {description: "Tejutepeque", pais_origens_id: 1},
  {description: "Victoria", pais_origens_id: 1},
  {description: "Apastepeque", pais_origens_id: 1},
  {description: "Guadalupe", pais_origens_id: 1},
  {description: "San Cayetano Istepeque", pais_origens_id: 1},
  {description: "San Esteban Catarina", pais_origens_id: 1},
  {description: "San Ildefonso", pais_origens_id: 1},
  {description: "San Lorenzo", pais_origens_id: 1},
  {description: "San Sebastián", pais_origens_id: 1},
  {description: "San Vicente", pais_origens_id: 1},
  {description: "Santa Clara", pais_origens_id: 1},
  {description: "Santo Domingo", pais_origens_id: 1},
  {description: "Tecoluca", pais_origens_id: 1},
  {description: "Tepetitán", pais_origens_id: 1},
  {description: "Verapaz", pais_origens_id: 1}
])

#User.create(name: "Administrador", description: nil, surname: nil, user_name: nil, password: "administrador2017", rol_id: 2, email: "administrador3@administrador.com", encrypted_password: "123", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 8, current_sign_in_at: "2017-09-10 20:02:15", last_sign_in_at: "2017-09-09 04:48:51", current_sign_in_ip: "::1", last_sign_in_ip: "::1")

















